// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.14.0
// source: grpc/flights/flights.proto

package flights

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filter string `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_flights_flights_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_flights_flights_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_grpc_flights_flights_proto_rawDescGZIP(), []int{0}
}

func (x *ListRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

type ListReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Year          int32   `protobuf:"varint,1,opt,name=Year,proto3" json:"Year,omitempty"`
	Month         int32   `protobuf:"varint,2,opt,name=Month,proto3" json:"Month,omitempty"`
	DayofMonth    int32   `protobuf:"varint,3,opt,name=DayofMonth,proto3" json:"DayofMonth,omitempty"`
	DayOfWeek     int32   `protobuf:"varint,4,opt,name=DayOfWeek,proto3" json:"DayOfWeek,omitempty"`
	DepTime       float32 `protobuf:"fixed32,5,opt,name=DepTime,proto3" json:"DepTime,omitempty"`
	CRSDepTime    int32   `protobuf:"varint,6,opt,name=CRSDepTime,proto3" json:"CRSDepTime,omitempty"`
	ArrTime       float32 `protobuf:"fixed32,7,opt,name=ArrTime,proto3" json:"ArrTime,omitempty"`
	CRSArrTime    int32   `protobuf:"varint,8,opt,name=CRSArrTime,proto3" json:"CRSArrTime,omitempty"`
	UniqueCarrier string  `protobuf:"bytes,9,opt,name=UniqueCarrier,proto3" json:"UniqueCarrier,omitempty"`
}

func (x *ListReply) Reset() {
	*x = ListReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_flights_flights_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReply) ProtoMessage() {}

func (x *ListReply) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_flights_flights_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReply.ProtoReflect.Descriptor instead.
func (*ListReply) Descriptor() ([]byte, []int) {
	return file_grpc_flights_flights_proto_rawDescGZIP(), []int{1}
}

func (x *ListReply) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *ListReply) GetMonth() int32 {
	if x != nil {
		return x.Month
	}
	return 0
}

func (x *ListReply) GetDayofMonth() int32 {
	if x != nil {
		return x.DayofMonth
	}
	return 0
}

func (x *ListReply) GetDayOfWeek() int32 {
	if x != nil {
		return x.DayOfWeek
	}
	return 0
}

func (x *ListReply) GetDepTime() float32 {
	if x != nil {
		return x.DepTime
	}
	return 0
}

func (x *ListReply) GetCRSDepTime() int32 {
	if x != nil {
		return x.CRSDepTime
	}
	return 0
}

func (x *ListReply) GetArrTime() float32 {
	if x != nil {
		return x.ArrTime
	}
	return 0
}

func (x *ListReply) GetCRSArrTime() int32 {
	if x != nil {
		return x.CRSArrTime
	}
	return 0
}

func (x *ListReply) GetUniqueCarrier() string {
	if x != nil {
		return x.UniqueCarrier
	}
	return ""
}

var File_grpc_flights_flights_proto protoreflect.FileDescriptor

var file_grpc_flights_flights_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x73, 0x2f, 0x66,
	0x6c, 0x69, 0x67, 0x68, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x66, 0x6c,
	0x69, 0x67, 0x68, 0x74, 0x73, 0x22, 0x25, 0x0a, 0x0b, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x22, 0x8d, 0x02, 0x0a,
	0x09, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x59, 0x65,
	0x61, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x59, 0x65, 0x61, 0x72, 0x12, 0x14,
	0x0a, 0x05, 0x4d, 0x6f, 0x6e, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x4d,
	0x6f, 0x6e, 0x74, 0x68, 0x12, 0x1e, 0x0a, 0x0a, 0x44, 0x61, 0x79, 0x6f, 0x66, 0x4d, 0x6f, 0x6e,
	0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x44, 0x61, 0x79, 0x6f, 0x66, 0x4d,
	0x6f, 0x6e, 0x74, 0x68, 0x12, 0x1c, 0x0a, 0x09, 0x44, 0x61, 0x79, 0x4f, 0x66, 0x57, 0x65, 0x65,
	0x6b, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x44, 0x61, 0x79, 0x4f, 0x66, 0x57, 0x65,
	0x65, 0x6b, 0x12, 0x18, 0x0a, 0x07, 0x44, 0x65, 0x70, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x07, 0x44, 0x65, 0x70, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a,
	0x43, 0x52, 0x53, 0x44, 0x65, 0x70, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0a, 0x43, 0x52, 0x53, 0x44, 0x65, 0x70, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x41, 0x72, 0x72, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x02, 0x52, 0x07, 0x41,
	0x72, 0x72, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x43, 0x52, 0x53, 0x41, 0x72, 0x72,
	0x54, 0x69, 0x6d, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x43, 0x52, 0x53, 0x41,
	0x72, 0x72, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x55, 0x6e, 0x69, 0x71, 0x75, 0x65,
	0x43, 0x61, 0x72, 0x72, 0x69, 0x65, 0x72, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x55,
	0x6e, 0x69, 0x71, 0x75, 0x65, 0x43, 0x61, 0x72, 0x72, 0x69, 0x65, 0x72, 0x32, 0x45, 0x0a, 0x0d,
	0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x34, 0x0a,
	0x04, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x14, 0x2e, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x73, 0x2e,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x66, 0x6c,
	0x69, 0x67, 0x68, 0x74, 0x73, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22,
	0x00, 0x30, 0x01, 0x42, 0x22, 0x5a, 0x20, 0x67, 0x6f, 0x2d, 0x67, 0x72, 0x70, 0x63, 0x2d, 0x61,
	0x70, 0x69, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x73, 0x2f,
	0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpc_flights_flights_proto_rawDescOnce sync.Once
	file_grpc_flights_flights_proto_rawDescData = file_grpc_flights_flights_proto_rawDesc
)

func file_grpc_flights_flights_proto_rawDescGZIP() []byte {
	file_grpc_flights_flights_proto_rawDescOnce.Do(func() {
		file_grpc_flights_flights_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpc_flights_flights_proto_rawDescData)
	})
	return file_grpc_flights_flights_proto_rawDescData
}

var file_grpc_flights_flights_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_grpc_flights_flights_proto_goTypes = []interface{}{
	(*ListRequest)(nil), // 0: flights.ListRequest
	(*ListReply)(nil),   // 1: flights.ListReply
}
var file_grpc_flights_flights_proto_depIdxs = []int32{
	0, // 0: flights.FlightService.List:input_type -> flights.ListRequest
	1, // 1: flights.FlightService.List:output_type -> flights.ListReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpc_flights_flights_proto_init() }
func file_grpc_flights_flights_proto_init() {
	if File_grpc_flights_flights_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpc_flights_flights_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_flights_flights_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_flights_flights_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_flights_flights_proto_goTypes,
		DependencyIndexes: file_grpc_flights_flights_proto_depIdxs,
		MessageInfos:      file_grpc_flights_flights_proto_msgTypes,
	}.Build()
	File_grpc_flights_flights_proto = out.File
	file_grpc_flights_flights_proto_rawDesc = nil
	file_grpc_flights_flights_proto_goTypes = nil
	file_grpc_flights_flights_proto_depIdxs = nil
}
