CREATE TABLE flights (
    Year INT,
    Month INT,
    DayofMonth INT,
    DayOfWeek INT,
    DepTime NUMERIC(8, 4),
    CRSDepTime INT,
    ArrTime NUMERIC(8, 4),
    CRSArrTime INT,
    UniqueCarrier VARCHAR(50),
    FlightNum INT,
    TailNum VARCHAR(50),
    ActualElapsedTime NUMERIC(8,4),
    CRSElapsedTime NUMERIC(8,4),
    AirTime NUMERIC(8,4),
    ArrDelay NUMERIC(8,4),
    DepDelay NUMERIC(8,4),
    Origin VARCHAR(50),
    Dest VARCHAR(50),
    Distance INT,
    TaxiIn NUMERIC(8,4),
    TaxiOut NUMERIC(8,4),
    Cancelled INT,
    CancellationCode VARCHAR(50),
    Diverted INT,
    CarrierDelay NUMERIC(8,4),
    WeatherDelay NUMERIC(8,4),
    NASDelay NUMERIC(8,4),
    SecurityDelay NUMERIC(8,4),
    LateAircraftDelay NUMERIC(8,4)
);
